### ISSUE TITLE
Sample application not workin

### ISSUE THREAD

**Issue by mudassirzulfiqar** [SmartWalkieOrg/VoicePing-Walkie-Talkie-AndroidSDK#10]
Hello Team, I have cloned the Android project, and built it on 2 different devices to test it.
When I press the big push-to-talk button I can see the following error in my code and it doesn't work?
`E/AudioEffect: set(): AudioFlinger could not create effect 58b4b260-8e06-11e0-aa8e-0002a5d5c51b / ec7178ec-e5e1-4432-a3f4-4657e6795210, status: -22
2022-07-12 13:29:04.037 11918-11918/com.smartwalkie.voicepingdemo E/AudioEffects-JNI: AudioEffect initCheck failed -3
2022-07-12 13:29:04.037 11918-11918/com.smartwalkie.voicepingdemo E/AudioEffect-JAVA: Error code -3 when initializing AudioEffect.`

Can you please guide?

**Comment by adityawibisana** [comment]
@mudassirzulfiqar : Thanks for trying our app.
1. Did you test with real device ?
2. Have you made sure that audio permission is enabled on your devices ?

**Comment by mudassirzulfiqar** [comment]
Hi, @adityawibisana Yeah I built the app on a real device, and I enabled Audio permission. Still no luck

**Comment by mudassirzulfiqar** [comment]
Hi, I have figured out, that I was entering the wrong Target User ID. Thanks
Nice Application
