### ISSUE TITLE
Cannot start talking from walkie talkie: "unauthorized group"?

### ISSUE THREAD

**Issue by anta40** [SmartWalkieOrg/VoicePing-Walkie-Talkie-AndroidSDK#12]
First I logged in at the [web interface](https://voiceping-router-test.netlify.app/) with following configuration:

- Company name: **TaskForceX**
- User ID: **Codename47**
- Server URL: **wss://router-lite.voiceping.info**

Clicked "Test Login", and I was in. I could see "user Codename47" on top left. With "GROUP" selected and **12345** as its value, I clicked "Set channel". I could see "group 12345"

Then on the Android app:

**LoginActivity**
- User ID: **Codename47**
- Company: **TaskForceX**
- Server URL: **wss://router-lite.voiceping.info**

Was able to logged in. Connection state was "CONNECTED". With "GROUP" as channel type and **12345** as group ID, I clicked join. Got the "Joined to 12345" message. And when I clicked the big red button, I got a "Please join the group first before sending PTT".  On the web interface, I could see "Unauthorized group" message.

Here's what I saw on Android Studio logcat:
```
2022-10-28 21:23:41.839  6497-6512  Recorder                com.smartwalkie.voicepingdemo        D  onMessageReceived: ACK_START
2022-10-28 21:23:41.848  6497-6512  Recorder                com.smartwalkie.voicepingdemo        D  onMessageReceived: UNAUTHORIZED_GROUP
2022-10-28 21:23:41.852  6497-6512  VoicePingButton         com.smartwalkie.voicepingdemo        D  onOutgoingTalkError, code: 7, message: UNAUTHORIZED_GROUP. Failed to initiate PTT Talk!
2022-10-28 21:23:41.853  6497-6512  Recorder                com.smartwalkie.voicepingdemo        D  onMessageReceived: ACK_START_FAILED
```

What's wrong here? Incorrect configuration?

**Comment by inovramadani** [comment]
@anta40 thank you for raising this issue. It's not related to configuration. There was backend service issue, I have just fixed it. It should be ok now, can you please retest?

Anyway you should have different user ID between devices (in this case the web and android).

**Comment by anta40** [comment]
Hi sorry for the very late reply. Busy working on another project. I have 2 Android test phones (different brand. One runs Android 10, and the other runs Android 12). Both already have the APK demo installed: https://github.com/SmartWalkieOrg/VoicePing-Walkie-Talkie-AndroidSDK/releases

On the 1st phone, here's my login information:
```
User ID = AWSM_001
Company = AWESOME1928
```

And on the 2nd phone:
```
User ID = AWSM_002
Company = AWESOME1928

```

OK, then let's create our group. On https://voiceping-router-test.netlify.app:
```
Company name: AWESOME1928
User ID: AWSM_003
Router URL: wss://router-lite.voiceping.info
```

Just created a group called 1928
![SCR-20230317-ulbv](https://user-images.githubusercontent.com/16976/225967308-a380b5cf-d577-4816-aa38-d266bf7de9b9.png)

On both Android phones, the connection status is "CONNECTED", e.g:
![vpp](https://user-images.githubusercontent.com/16976/225968288-a488606e-1235-405e-ab28-0ea906690e4d.jpeg)

And also I've joined to the group 1928 on both phones. There's a "Joined to 1928" popup. But when I pressed the PTT button, I got this message: "Please join the group first before sending PTT"

I already did that. Perhaps I'm missing something?

**Comment by alessandrogriggio** [comment]
Same problems of @anta40

**Comment by dhianpratama** [comment]
Hi @anta40 @alessandrogriggio 

The problem has been fixed. Our server for `wss://router-lite.voiceping.info` was not updated with the latest code. Please try again.

Thanks

**Comment by thoyyu** [comment]
@dhianpratama can you push this code update to the 'voiceping-router' Github repo
https://github.com/SmartWalkieOrg/voiceping-router
